/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ryanbair (https://sketchfab.com/ryanbair)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nike-dunk-dusty-olive-metashape-a9acc1e575bd43f683643c824d507bfe
title: Nike Dunk Dusty Olive Metashape
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/raw-models/second/scene.gltf')
  return (
    <group {...props} dispose={null}>

        <group rotation={[-Math.PI / 4, 3.6, 0.3]} scale={5.5} position={[-7.8, 7.4, -36.8]}>
          <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_1.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_2.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_3.geometry} material={materials.material0} />
        </group>

    </group>
  )
}

useGLTF.preload('/raw-models/second/scene.gltf')
